import '../../Model/menuItemModel.dart';


final List<MenuItemModel> menuSeedItems = [
	// Nut-Free
	MenuItemModel(
		uid: '31',
		name: 'Nut Free Brownie',
		description: 'Delicious chocolate brownie made without nuts.',
		price: 4.49,
		imageUrl: 'assets/images/NutFreeBrownie.png',
		category: ['Dessert', 'Food'],
		isAvailable: true,
		calories: '390',
		menuTags: ['Dessert'],
		dietaryTags: ['Nut-Free', 'Vegetarian'],
	),
	// Dairy-Free
	MenuItemModel(
		uid: '32',
		name: 'Dairy Free Latte',
		description: 'Espresso with oat milk, no dairy.',
		price: 3.99,
		imageUrl: 'assets/images/DairyFreeLatte.png',
		category: ['Drink'],
		isAvailable: true,
		calories: '80',
		menuTags: ['Classic'],
		dietaryTags: ['Dairy-Free', 'Vegan'],
	),
	// Low-Carb
	MenuItemModel(
		uid: '33',
		name: 'Low Carb Salad',
		description: 'Fresh salad with low-carb veggies and grilled chicken.',
		price: 7.49,
		imageUrl: 'assets/images/LowCarbSalad.png',
		category: ['Food'],
		isAvailable: true,
		calories: '180',
		menuTags: ['New'],
		dietaryTags: ['Low-Carb', 'Halal'],
	),
	// Low-Fat
	MenuItemModel(
		uid: '34',
		name: 'Low Fat Yogurt',
		description: 'Creamy yogurt with low fat content.',
		price: 2.99,
		imageUrl: 'assets/images/LowFatYogurt.png',
		category: ['Dessert'],
		isAvailable: true,
		calories: '90',
		menuTags: ['Dessert'],
		dietaryTags: ['Low-Fat', 'Vegetarian'],
	),
	// Low-Sugar
	MenuItemModel(
		uid: '35',
		name: 'Low Sugar Lemonade',
		description: 'Lemonade with reduced sugar.',
		price: 2.79,
		imageUrl: 'assets/images/LowSugarLemonade.png',
		category: ['Drink', 'Non-Alcoholic'],
		isAvailable: true,
		calories: '40',
		menuTags: ['Seasonal'],
		dietaryTags: ['Low-Sugar', 'Vegan'],
	),
	// Low ABV
	MenuItemModel(
		uid: '36',
		name: 'Low ABV Spritz',
		description: 'Aperitif spritz with low alcohol by volume.',
		price: 6.49,
		imageUrl: 'assets/images/LowABVSpritz.png',
		category: ['Drink', 'Alcohol'],
		isAvailable: true,
		calories: '110',
		menuTags: ['Low ABV', 'Craft'],
		dietaryTags: ['Vegan'],
	),
	// High ABV
	MenuItemModel(
		uid: '37',
		name: 'High ABV Stout',
		description: 'Strong stout beer with high alcohol content.',
		price: 7.49,
		imageUrl: 'assets/images/HighABVStout.png',
		category: ['Drink', 'Alcohol'],
		isAvailable: true,
		calories: '210',
		menuTags: ['High ABV', 'Classic'],
		dietaryTags: ['Vegan'],
	),
	// For The Long Haul
	MenuItemModel(
		uid: '38',
		name: 'Long Haul Platter',
		description: 'A big platter for long gaming sessions.',
		price: 15.99,
		imageUrl: 'assets/images/LongHaulPlatter.png',
		category: ['Combo', 'Food'],
		isAvailable: true,
		calories: '1200',
		menuTags: ['For The Long Haul'],
		dietaryTags: ['Halal'],
	),
	// Goes With Everything
	MenuItemModel(
		uid: '39',
		name: 'French Fries',
		description: 'Crispy fries that go with any meal.',
		price: 3.49,
		imageUrl: 'assets/images/FrenchFries.png',
		category: ['Side'],
		isAvailable: true,
		calories: '320',
		menuTags: ['Goes With Everything'],
		dietaryTags: ['Vegan'],
	),
	// Better Before Game
	MenuItemModel(
		uid: '40',
		name: 'Energy Bar',
		description: 'Nutritious bar to fuel your game.',
		price: 2.49,
		imageUrl: 'assets/images/EnergyBar.png',
		category: ['Food'],
		isAvailable: true,
		calories: '180',
		menuTags: ['Better Before Game'],
		dietaryTags: ['Vegetarian'],
	),
	// Not Just For Kids
	MenuItemModel(
		uid: '41',
		name: 'Chocolate Milk',
		description: 'Classic chocolate milk for all ages.',
		price: 2.99,
		imageUrl: 'assets/images/ChocolateMilk.png',
		category: ['Drink', 'Non-Alcoholic'],
		isAvailable: true,
		calories: '160',
		menuTags: ['Not Just For Kids'],
		dietaryTags: ['Vegetarian'],
	),
	// Craft
	// MenuItemModel(
	// 	uid: '42',
	// 	name: 'Craft Cola',
	// 	description: 'Handcrafted cola with unique spices.',
	// 	price: 3.29,
	// 	imageUrl: 'assets/images/CraftCola.png',
	// 	category: ['Drink', 'Non-Alcoholic'],
	// 	isAvailable: true,
	// 	calories: '120',
	// 	menuTags: ['Craft'],
	// 	dietaryTags: ['Vegan'],
	// ),
	// Seasonal
	MenuItemModel(
		uid: '43',
		name: 'Pumpkin Soup',
		description: 'Creamy pumpkin soup, perfect for autumn.',
		price: 5.49,
		imageUrl: 'assets/images/PumpkinSoup.png',
		category: ['Food'],
		isAvailable: true,
		calories: '140',
		menuTags: ['Seasonal'],
		dietaryTags: ['Vegetarian'],
	),
	// New
	MenuItemModel(
		uid: '44',
		name: 'New Vegan Wrap',
		description: 'Fresh vegan wrap with seasonal veggies.',
		price: 6.99,
		imageUrl: 'assets/images/NewVeganWrap.png',
		category: ['Food'],
		isAvailable: true,
		calories: '260',
		menuTags: ['New'],
		dietaryTags: ['Vegan'],
	),
	// Dessert
	MenuItemModel(
		uid: '45',
		name: 'Apple Pie',
		description: 'Classic apple pie with a flaky crust.',
		price: 4.29,
		imageUrl: 'assets/images/ApplePie.png',
		category: ['Dessert', 'Food'],
		isAvailable: true,
		calories: '320',
		menuTags: ['Dessert'],
		dietaryTags: ['Vegetarian'],
	),
];

// /// List of menu items to populate the menu page. Add your items here.
// final List<MenuItemModel> menuSeedItems = [
//   MenuItemModel(
//     uid: '1',
//     name: 'Espresso',
//     description: 'Strong and bold Italian coffee.',
//     price: 2.99,
//     imageUrl: 'assets/images/Espresso.png',
//     category: ['Drink'],
//     isAvailable: true,
//     calories: '5',
//     menuTags: ['Classic'],
//     dietaryTags: ['Vegan'],
//   ),
//   MenuItemModel(
//     uid: '2',
//     name: 'Vegan Burger',
//     description: 'Plant-based burger with fresh veggies.',
//     price: 8.99,
//     imageUrl: 'assets/images/VeganBurger.png',
//     category: ['Food'],
//     isAvailable: true,
//     calories: '420',
//     menuTags: ['New'],
//     dietaryTags: ['Vegan'],
//   ),
//   MenuItemModel(
//     uid: '3',
//     name: 'Caesar Salad',
//     description: 'Crisp romaine, parmesan, and croutons.',
//     price: 6.49,
//     imageUrl: 'assets/images/CaesarSalad.png',
//     category: ['Food'],
//     isAvailable: true,
//     calories: '250',
//     menuTags: ['Classic'],
//     dietaryTags: ['Vegetarian'],
//   ),
//   MenuItemModel(
//     uid: '4',
//     name: 'Margarita',
//     description: 'Classic tequila cocktail with lime.',
//     price: 7.99,
//     imageUrl: 'assets/images/Margarita.png',
//     category: ['Cocktail', 'Alcohol'],
//     isAvailable: true,
//     calories: '200',
//     menuTags: ['Craft'],
//     dietaryTags: ['Gluten-Free'],
//   ),
//   MenuItemModel(
//     uid: '5',
//     name: 'Combo Platter',
//     description: 'A mix of our best snacks.',
//     price: 12.99,
//     imageUrl: 'assets/images/ComboPlatter.png',
//     category: ['Combo'],
//     isAvailable: true,
//     calories: '800',
//     menuTags: ['For The Long Haul'],
//     dietaryTags: ['Halal'],
//   ),
//   MenuItemModel(
//     uid: '6',
//     name: 'Orange Juice',
//     description: 'Freshly squeezed orange juice.',
//     price: 3.49,
//     imageUrl: 'assets/images/OrangeJuice.png',
//     category: ['Drink', 'Non-Alcoholic'],
//     isAvailable: true,
//     calories: '110',
//     menuTags: ['Seasonal'],
//     dietaryTags: ['Vegan', 'Gluten-Free'],
//   ),
//   MenuItemModel(
//     uid: '7',
//     name: 'Chocolate Cake',
//     description: 'Rich and moist chocolate dessert.',
//     price: 4.99,
//     imageUrl: 'assets/images/ChocolateCake.png',
//     category: ['Dessert', 'Food'],
//     isAvailable: true,
//     calories: '450',
//     menuTags: ['Dessert'],
//     dietaryTags: ['Vegetarian'],
//   ),
//   MenuItemModel(
//     uid: '8',
//     name: 'Fish And Chips',
//     description: 'Crispy battered fish with fries.',
//     price: 9.99,
//     imageUrl: 'assets/images/FishAndChips.png',
//     category: ['Food'],
//     isAvailable: true,
//     calories: '600',
//     menuTags: ['Classic'],
//     dietaryTags: ['Pescatarian'],
//   ),
//   MenuItemModel(
//     uid: '9',
//     name: 'Side Salad',
//     description: 'Light salad with vinaigrette.',
//     price: 3.99,
//     imageUrl: 'assets/images/SideSalad.png',
//     category: ['Side'],
//     isAvailable: true,
//     calories: '90',
//     menuTags: ['Goes With Everything'],
//     dietaryTags: ['Vegan', 'Gluten-Free'],
//   ),
//   MenuItemModel(
//     uid: '10',
//     name: 'IPA Beer',
//     description: 'Hoppy craft India Pale Ale.',
//     price: 5.99,
//     imageUrl: 'assets/images/IPABeer.png',
//     category: ['Drink', 'Alcohol'],
//     isAvailable: true,
//     calories: '180',
//     menuTags: ['Craft', 'High ABV'],
//     dietaryTags: ['Vegan'],
//   ),
//   // More items for variety and all categories
//   MenuItemModel(
//     uid: '11',
//     name: 'Latte',
//     description: 'Smooth espresso with steamed milk.',
//     price: 3.49,
//     imageUrl: 'assets/images/Latte.png',
//     category: ['Drink'],
//     isAvailable: true,
//     calories: '120',
//     menuTags: ['Classic'],
//     dietaryTags: ['Vegetarian'],
//   ),
//   MenuItemModel(
//     uid: '12',
//     name: 'Chicken Wrap',
//     description: 'Grilled chicken with veggies in a wrap.',
//     price: 7.49,
//     imageUrl: 'assets/images/ChickenWrap.png',
//     category: ['Food'],
//     isAvailable: true,
//     calories: '350',
//     menuTags: ['New'],
//     dietaryTags: ['Halal'],
//   ),
//   MenuItemModel(
//     uid: '13',
//     name: 'Mozzarella Sticks',
//     description: 'Fried mozzarella cheese sticks.',
//     price: 5.99,
//     imageUrl: 'assets/images/MozzarellaSticks.png',
//     category: ['Side'],
//     isAvailable: true,
//     calories: '400',
//     menuTags: ['Goes With Everything'],
//     dietaryTags: ['Vegetarian'],
//   ),
//   MenuItemModel(
//     uid: '14',
//     name: 'Fruit Salad',
//     description: 'Fresh seasonal fruits.',
//     price: 4.49,
//     imageUrl: 'assets/images/FruitSalad.png',
//     category: ['Dessert'],
//     isAvailable: true,
//     calories: '150',
//     menuTags: ['Dessert'],
//     dietaryTags: ['Vegan', 'Gluten-Free'],
//   ),
//   MenuItemModel(
//     uid: '15',
//     name: 'Club Sandwich',
//     description: 'Triple layered sandwich with chicken, bacon, and veggies.',
//     price: 8.49,
//     imageUrl: 'assets/images/ClubSandwich.png',
//     category: ['Food'],
//     isAvailable: true,
//     calories: '550',
//     menuTags: ['Classic'],
//     dietaryTags: ['Halal'],
//   ),
//   MenuItemModel(
//     uid: '16',
//     name: 'Lemonade',
//     description: 'Refreshing homemade lemonade.',
//     price: 2.99,
//     imageUrl: 'assets/images/Lemonade.png',
//     category: ['Drink', 'Non-Alcoholic'],
//     isAvailable: true,
//     calories: '90',
//     menuTags: ['Seasonal'],
//     dietaryTags: ['Vegan'],
//   ),
//   MenuItemModel(
//     uid: '17',
//     name: 'Brownie Sundae',
//     description: 'Warm brownie with ice cream and chocolate sauce.',
//     price: 5.49,
//     imageUrl: 'assets/images/BrownieSundae.png',
//     category: ['Dessert'],
//     isAvailable: true,
//     calories: '520',
//     menuTags: ['Dessert'],
//     dietaryTags: ['Vegetarian'],
//   ),
//   MenuItemModel(
//     uid: '18',
//     name: 'Nachos',
//     description: 'Tortilla chips with cheese and salsa.',
//     price: 6.99,
//     imageUrl: 'assets/images/Nachos.png',
//     category: ['Side', 'Combo'],
//     isAvailable: true,
//     calories: '480',
//     menuTags: ['For The Long Haul'],
//     dietaryTags: ['Vegetarian'],
//   ),
//   MenuItemModel(
//     uid: '19',
//     name: 'Gin Tonic',
//     description: 'Classic gin and tonic cocktail.',
//     price: 8.49,
//     imageUrl: 'assets/images/GinTonic.png',
//     category: ['Cocktail', 'Alcohol'],
//     isAvailable: true,
//     calories: '170',
//     menuTags: ['Craft'],
//     dietaryTags: ['Gluten-Free'],
//   ),
//   MenuItemModel(
//     uid: '20',
//     name: 'Veggie Pizza',
//     description: 'Pizza topped with fresh vegetables.',
//     price: 10.99,
//     imageUrl: 'assets/images/VeggiePizza.png',
//     category: ['Food'],
//     isAvailable: true,
//     calories: '700',
//     menuTags: ['Classic'],
//     dietaryTags: ['Vegetarian'],
//   ),
//   MenuItemModel(
//     uid: '21',
//     name: 'Coke',
//     description: 'Classic Coca-Cola soft drink.',
//     price: 2.49,
//     imageUrl: 'assets/images/Coke.png',
//     category: ['Drink', 'Non-Alcoholic'],
//     isAvailable: true,
//     calories: '140',
//     menuTags: ['Classic'],
//     dietaryTags: ['Vegan', 'Gluten-Free'],
//   ),
//   MenuItemModel(
//     uid: '22',
//     name: 'Beer',
//     description: 'Refreshing lager beer.',
//     price: 4.99,
//     imageUrl: 'assets/images/Beer.png',
//     category: ['Drink', 'Alcohol'],
//     isAvailable: true,
//     calories: '150',
//     menuTags: ['Classic'],
//     dietaryTags: ['Vegan'],
//   ),
//   MenuItemModel(
//     uid: '23',
//     name: 'Double Burger Meal',
//     description: 'Two juicy burgers with fries and a drink.',
//     price: 13.99,
//     imageUrl: 'assets/images/DoubleBurgerMeal.png',
//     category: ['Combo', 'Food'],
//     isAvailable: true,
//     calories: '1100',
//     menuTags: ['For The Long Haul'],
//     dietaryTags: ['Halal'],
//   ),
//   MenuItemModel(
//     uid: '24',
//     name: 'Burger Meal',
//     description: 'Burger with fries and a drink.',
//     price: 10.99,
//     imageUrl: 'assets/images/BurgerMeal.png',
//     category: ['Combo', 'Food'],
//     isAvailable: true,
//     calories: '900',
//     menuTags: ['Classic'],
//     dietaryTags: ['Halal'],
//   ),
//   MenuItemModel(
//     uid: '25',
//     name: 'Hotdog',
//     description: 'Grilled hotdog in a bun with toppings.',
//     price: 5.49,
//     imageUrl: 'assets/images/Hotdog.png',
//     category: ['Food'],
//     isAvailable: true,
//     calories: '350',
//     menuTags: ['Classic'],
//     dietaryTags: ['Halal'],
//   ),
//   MenuItemModel(
//     uid: '26',
//     name: 'Wings',
//     description: 'Spicy chicken wings with dip.',
//     price: 7.99,
//     imageUrl: 'assets/images/Wings.png',
//     category: ['Food', 'Side'],
//     isAvailable: true,
//     calories: '600',
//     menuTags: ['New'],
//     dietaryTags: ['Halal'],
//   ),
//   MenuItemModel(
//     uid: '27',
//     name: 'Vegan Platter',
//     description: 'A selection of vegan snacks and dips.',
//     price: 11.99,
//     imageUrl: 'assets/images/VeganPlatter.png',
//     category: ['Combo', 'Food'],
//     isAvailable: true,
//     calories: '700',
//     menuTags: ['For The Long Haul'],
//     dietaryTags: ['Vegan'],
//   ),
//   MenuItemModel(
//     uid: '28',
//     name: 'Hashbrowns',
//     description: 'Crispy golden hashbrowns.',
//     price: 3.49,
//     imageUrl: 'assets/images/Hashbrowns.png',
//     category: ['Side'],
//     isAvailable: true,
//     calories: '220',
//     menuTags: ['Goes With Everything'],
//     dietaryTags: ['Vegan'],
//   ),
//   MenuItemModel(
//     uid: '29',
//     name: 'Mixed Dips Sauce',
//     description: 'A trio of house-made dips.',
//     price: 2.99,
//     imageUrl: 'assets/images/MixedDipsSauce.png',
//     category: ['Side'],
//     isAvailable: true,
//     calories: '100',
//     menuTags: ['Goes With Everything'],
//     dietaryTags: ['Vegetarian'],
//   ),
//   MenuItemModel(
//     uid: '30',
//     name: 'Cheesy Sticks',
//     description: 'Warm breadsticks stuffed with cheese.',
//     price: 4.99,
//     imageUrl: 'assets/images/CheesySticks.png',
//     category: ['Side', 'Food'],
//     isAvailable: true,
//     calories: '350',
//     menuTags: ['Goes With Everything'],
//     dietaryTags: ['Vegetarian'],
//   ),
//   MenuItemModel(
//     uid: '17',
//     name: 'Brownie Sundae',
//     description: 'Warm brownie with ice cream and chocolate sauce.',
//     price: 5.49,
//     imageUrl: 'assets/images/BrownieSundae.png',
//     category: ['Dessert'],
//     isAvailable: true,
//     calories: '520',
//     menuTags: ['Dessert'],
//     dietaryTags: ['Vegetarian'],
//   ),
//   MenuItemModel(
//     uid: '18',
//     name: 'Nachos',
//     description: 'Tortilla chips with cheese and salsa.',
//     price: 6.99,
//     imageUrl: 'assets/images/Nachos.png',
//     category: ['Side', 'Combo'],
//     isAvailable: true,
//     calories: '480',
//     menuTags: ['For The Long Haul'],
//     dietaryTags: ['Vegetarian'],
//   ),
//   MenuItemModel(
//     uid: '19',
//     name: 'Gin Tonic',
//     description: 'Classic gin and tonic cocktail.',
//     price: 8.49,
//     imageUrl: 'assets/images/GinTonic.png',
//     category: ['Cocktail', 'Alcohol'],
//     isAvailable: true,
//     calories: '170',
//     menuTags: ['Craft'],
//     dietaryTags: ['Gluten-Free'],
//   ),
//   MenuItemModel(
//     uid: '20',
//     name: 'Veggie Pizza',
//     description: 'Pizza topped with fresh vegetables.',
//     price: 10.99,
//     imageUrl: 'assets/images/VeggiePizza.png',
//     category: ['Food'],
//     isAvailable: true,
//     calories: '700',
//     menuTags: ['Classic'],
//     dietaryTags: ['Vegetarian'],
//   ),
// ];
